apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: aoe2companion-«-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - «.aoe2companion.com
      secretName: «-aoe2companion-com-tls
  rules:
    - host: «.aoe2companion.com
      http:
        paths:
          - backend:
              serviceName: aoe2companion-«
              servicePort: 80