inputs:
  name:
    description: 'Your name'
    default: 'No name provided'
runs:
  using: "composite"
  steps:
    - run: |
        echo "COMMIT_SHA1=$GITHUB_SHA" >> $GITHUB_ENV
        echo "TRAVIS_BRANCH=$(node deploy/script/clean-tag.js $GITHUB_REF)" >> $GITHUB_ENV
      shell: bash

# echo "DOCKERHUB_USERNAME=$(secrethub read denniske/dockerhub/username)" >> $GITHUB_ENV
