apiVersion: apps/v1
kind: Deployment
metadata:
  name: aoe2companion-proxy
  namespace: default
  labels:
    app: aoe2companion-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aoe2companion-proxy
  template:
    metadata:
      labels:
        app: aoe2companion-proxy
    spec:
      containers:
        - name: aoe2companion-proxy
          image: denniske/aoe2companion-proxy:$COMMIT_SHA1
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - secretRef:
                name: server-secret
          env:
            - name: PORT
              value: "80"
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name