# https://hackernoon.com/the-only-sane-way-to-setup-fastlane-on-a-mac-4a14cb8549c8

on: push

name: App

env:
  NODE_VERSION: 12.13.1
  EXPO_SDK_VERSION: 38.0.0
  EXPO_CLI_VERSION: 3.27.4
  TURTLE_VERSION: 0.17.1

jobs:

#  publish:
#    name: Publish
#    runs-on: ubuntu-latest
#    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0')
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: Setup Env
#        uses: ./.github/actions/setup
#      - name: Setup Node
#        uses: actions/setup-node@v2.1.2
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#      - name: Setup Secrets
#        uses: secrethub/actions/env-export@v0.2.1
#        env:
#          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}
#          EXPO_USERNAME: secrethub://denniske/aoe2companion/expo_username
#          EXPO_PASSWORD: secrethub://denniske/aoe2companion/expo_password
#
#      - uses: expo/expo-github-action@v5
#        with:
#          expo-version: ${{ env.EXPO_CLI_VERSION }}
#          expo-username: ${{ env.EXPO_USERNAME }}
#          expo-password: ${{ env.EXPO_PASSWORD }}
#      - run: yarn
#      - run: npx expo publish --release-channel $CHANNEL

  build:
    name: Build
    runs-on: ubuntu-latest
#    needs: [publish]
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0')
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Env
        uses: ./.github/actions/setup
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Secrets
        uses: secrethub/actions/env-export@v0.2.1
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}
          EXPO_ANDROID_KEYSTORE_BASE64: secrethub://denniske/aoe2companion/expo_android_keystore_base64
          EXPO_ANDROID_KEYSTORE_ALIAS: secrethub://denniske/aoe2companion/expo_android_keystore_alias
          EXPO_ANDROID_KEYSTORE_PASSWORD: secrethub://denniske/aoe2companion/expo_android_keystore_password
          EXPO_ANDROID_KEY_PASSWORD: secrethub://denniske/aoe2companion/expo_android_key_password

      - run: sudo yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
      - run: turtle setup:android --sdk-version $EXPO_SDK_VERSION > /dev/null
      - run: yarn
      - run: |
          echo $EXPO_ANDROID_KEYSTORE_BASE64 > expo-project.jks.base64
          base64 --decode expo-project.jks.base64 > expo-project.jks
          ls -al
      - run: |
          turtle build:android
            --config app.json
            --release-channel $CHANNEL
            --keystore-path ./expo-project.jks
            --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS
            --type app-bundle
            -o expo-project-$TRAVIS_COMMIT.aab

      - name: Upload AAB
        uses: actions/upload-artifact@v1
        with:
          name: AAB
          path: expo-project-$TRAVIS_COMMIT.aab

#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    needs: [build]
#    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0.0')
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
