# https://hackernoon.com/the-only-sane-way-to-setup-fastlane-on-a-mac-4a14cb8549c8

on: push

name: App
env:
  NODE_VERSION: 12.13.1
jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Env
        uses: ./.github/actions/setup
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Secrets
        uses: secrethub/actions/env-export@v0.2.1
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}
          EXPO_USERNAME: secrethub://denniske/aoe2companion/expo_username
          EXPO_PASSWORD: secrethub://denniske/aoe2companion/expo_password
#      - run: yarn
#      - run: echo $TRAVIS_BRANCH
#      - run: echo "CHANNEL=$(node deploy/script/channel-from-tag.js $TRAVIS_BRANCH)" >> $GITHUB_ENV
#      - run: echo $CHANNEL
#      - run: npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive
#      - run: npx expo publish --release-channel $CHANNEL

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [publish]
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0')
    steps:
      - name: Checkout
        uses: actions/checkout@v1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0.0')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
