# https://hackernoon.com/the-only-sane-way-to-setup-fastlane-on-a-mac-4a14cb8549c8

on: push

name: App

env:
  NODE_VERSION: 12.18.0
  EXPO_SDK_VERSION: 40.0.1
  EXPO_CLI_VERSION: 4.0.17
  TURTLE_VERSION: 0.20.4
  SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Env
        uses: ./.github/actions/setup
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Secrets
        uses: secrethub/actions/env-export@v0.2.1
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}
          EXPO_USERNAME: secrethub://denniske/aoe2companion/expo_username
          EXPO_PASSWORD: secrethub://denniske/aoe2companion/expo_password

      - uses: expo/expo-github-action@v5
        with:
          expo-version: ${{ env.EXPO_CLI_VERSION }}
          expo-username: ${{ env.EXPO_USERNAME }}
          expo-password: ${{ env.EXPO_PASSWORD }}
      - run: yarn
      - run: npx expo publish --release-channel $CHANNEL


  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [publish]
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0')
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Env
        uses: ./.github/actions/setup
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Secrets
        uses: secrethub/actions/env-export@v0.2.1
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}
          EXPO_USERNAME: secrethub://denniske/aoe2companion/expo_username
          EXPO_PASSWORD: secrethub://denniske/aoe2companion/expo_password
          EXPO_ANDROID_KEYSTORE_BASE64: secrethub://denniske/aoe2companion/expo_android_keystore_base64
          EXPO_ANDROID_KEYSTORE_ALIAS: secrethub://denniske/aoe2companion/expo_android_keystore_alias
          EXPO_ANDROID_KEYSTORE_PASSWORD: secrethub://denniske/aoe2companion/expo_android_keystore_password
          EXPO_ANDROID_KEY_PASSWORD: secrethub://denniske/aoe2companion/expo_android_key_password

      - run: yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
      - run: yarn
      - run: turtle setup:android --sdk-version $EXPO_SDK_VERSION > /dev/null
      - run: echo $EXPO_ANDROID_KEYSTORE_BASE64 | base64 --decode > expo-project.jks
      - run: "
          turtle build:android
            --config app.json
            --release-channel $CHANNEL
            --keystore-path ./expo-project.jks
            --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS
            --type app-bundle
            -o expo-project-$TRAVIS_COMMIT.aab
        "

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: expo-project-${{ env.TRAVIS_COMMIT }}.aab
          path: expo-project-${{ env.TRAVIS_COMMIT }}.aab


  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: [publish]
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0')
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Env
        uses: ./.github/actions/setup
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.NODE_VERSION }}

#      - name: Setup Secrets
#        uses: secrethub/actions/env-export@v0.2.1
#        env:
#          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}
#          EXPO_USERNAME: secrethub://denniske/aoe2companion/expo_username
#          EXPO_PASSWORD: secrethub://denniske/aoe2companion/expo_password
#          EXPO_APPLE_TEAM_ID: secrethub://denniske/aoe2companion/expo_apple_team_id
#          EXPO_IOS_DIST_P12_PASSWORD: secrethub://denniske/aoe2companion/expo_ios_dist_p12_password
#          EXPO_IOS_DIST_P12_BASE64: secrethub://denniske/aoe2companion/expo_ios_dist_p12_base64
#          EXPO_IOS_PROVISIONING_PROFILE_BASE64: secrethub://denniske/aoe2companion/expo_ios_provisioning_profile_base64

      - run: brew install secrethub/tools/secrethub-cli

#      - run: brew install secrethub/tools/secrethub-cli

#      - run: secrethub read denniske/aoe2companion/expo_username
#      - run: secrethub read denniske/aoe2companion/expo_password
#      - run: secrethub read denniske/aoe2companion/expo_apple_team_id
#      - run: secrethub read denniske/aoe2companion/expo_ios_dist_p12_password
#      - run: secrethub read denniske/aoe2companion/expo_ios_dist_p12_base64
#      - run: secrethub read denniske/aoe2companion/expo_ios_provisioning_profile_base64

#      - run: echo "EXPO_USERNAME=$(secrethub read denniske/aoe2companion/expo_username)" >> $GITHUB_ENV
#      - run: echo "EXPO_PASSWORD=$(secrethub read denniske/aoe2companion/expo_password)" >> $GITHUB_ENV
#      - run: echo "EXPO_APPLE_TEAM_ID=$(secrethub read denniske/aoe2companion/expo_apple_team_id)" >> $GITHUB_ENV
#      - run: echo "EXPO_IOS_DIST_P12_PASSWORD=$(secrethub read denniske/aoe2companion/expo_ios_dist_p12_password)" >> $GITHUB_ENV
#      - run: echo "EXPO_IOS_DIST_P12_BASE64=$(secrethub read denniske/aoe2companion/expo_ios_dist_p12_base64)" >> $GITHUB_ENV
#      - run: echo "EXPO_IOS_PROVISIONING_PROFILE_BASE64=$(secrethub read denniske/aoe2companion/expo_ios_prov_profile_base64)" >> $GITHUB_ENV

      - run: |
          echo "EXPO_USERNAME=$(secrethub read denniske/aoe2companion/expo_username)" >> $GITHUB_ENV
          echo "EXPO_PASSWORD=$(secrethub read denniske/aoe2companion/expo_password)" >> $GITHUB_ENV
          echo "EXPO_APPLE_TEAM_ID=$(secrethub read denniske/aoe2companion/expo_apple_team_id)" >> $GITHUB_ENV
          echo "EXPO_IOS_DIST_P12_PASSWORD=$(secrethub read denniske/aoe2companion/expo_ios_dist_p12_password)" >> $GITHUB_ENV
          echo "EXPO_IOS_DIST_P12_BASE64=$(secrethub read denniske/aoe2companion/expo_ios_dist_p12_base64)" >> $GITHUB_ENV
          echo "EXPO_IOS_PROVISIONING_PROFILE_BASE64=$(secrethub read denniske/aoe2companion/expo_ios_prov_profile_base64)" >> $GITHUB_ENV

      - run: yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
      - run: yarn
      - run: turtle setup:ios --sdk-version $EXPO_SDK_VERSION > /dev/null
      - run: echo $EXPO_IOS_DIST_P12_BASE64 | base64 --decode > expo-project_dist.p12
      - run: echo $EXPO_IOS_PROVISIONING_PROFILE_BASE64 | base64 --decode > expo-project.mobileprovision
      - run: "
          turtle build:ios
            --config app.json
            --release-channel $CHANNEL
            --team-id \"$EXPO_APPLE_TEAM_ID\"
            --dist-p12-path ./expo-project_dist.p12
            --provisioning-profile-path ./expo-project.mobileprovision
            -o expo-project-$TRAVIS_COMMIT.ipa
        "

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: expo-project-${{ env.TRAVIS_COMMIT }}.ipa
          path: expo-project-${{ env.TRAVIS_COMMIT }}.ipa

#        - echo $EXPO_IOS_DIST_P12_BASE64 > expo-project_dist.p12.base64
#        - base64 --decode expo-project_dist.p12.base64 > expo-project_dist.p12
#        - echo $EXPO_IOS_PROVISIONING_PROFILE_BASE64 > expo-project.mobileprovision.base64
#        - base64 --decode expo-project.mobileprovision.base64 > expo-project.mobileprovision
#        - ls -al
#        - turtle build:ios
#            --config app.json
#            --release-channel $CHANNEL
#            -o $ARTIFACT_PATH

# Deployment
#        - export ARTIFACT_PATH="/Users/travis/expo-project-$TRAVIS_COMMIT.ipa"
#        - turtle setup:ios --sdk-version $EXPO_SDK_VERSION || travis_terminate 1
#        - aws s3 cp s3://$AWS_BUCKET/`basename $ARTIFACT_PATH` app.ipa
#        - ls -al
#        - cd app/ios
#        - travis_wait 30 fastlane build_and_deploy_testflight























#  build2:
#    name: Build
#    runs-on: ubuntu-latest
##    needs: [publish]
#    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0')
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#
#      - name: Setup Env
#        uses: ./.github/actions/setup
#      - name: Setup Node
#        uses: actions/setup-node@v2.1.2
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#      - name: Setup Secrets
#        uses: secrethub/actions/env-export@v0.2.1
#        env:
#          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}
#          EXPO_ANDROID_KEYSTORE_BASE64: secrethub://denniske/aoe2companion/expo_android_keystore_base64
#          EXPO_ANDROID_KEYSTORE_ALIAS: secrethub://denniske/aoe2companion/expo_android_keystore_alias
#          EXPO_ANDROID_KEYSTORE_PASSWORD: secrethub://denniske/aoe2companion/expo_android_keystore_password
#          EXPO_ANDROID_KEY_PASSWORD: secrethub://denniske/aoe2companion/expo_android_key_password
#
#      - run: unset NPM_CONFIG_USER
#      - run: sudo yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
#      - run: yarn
#      - run: turtle setup:android --sdk-version $EXPO_SDK_VERSION > /dev/null
#      - run: |
#          echo $EXPO_ANDROID_KEYSTORE_BASE64 > expo-project.jks.base64
#          base64 --decode expo-project.jks.base64 > expo-project.jks
#          ls -al
#      - run: |
#          turtle build:android
#            --config app.json
#            --release-channel $CHANNEL
#            --keystore-path ./expo-project.jks
#            --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS
#            --type app-bundle
#            -o expo-project-$TRAVIS_COMMIT.aab
#
#      - name: Upload AAB
#        uses: actions/upload-artifact@v1
#        with:
#          name: AAB
#          path: expo-project-$TRAVIS_COMMIT.aab
#
#  build3:
#    name: Build
#    runs-on: ubuntu-latest
##    needs: [publish]
#    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0')
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#
#      - name: Setup Env
#        uses: ./.github/actions/setup
#      - name: Setup Node
#        uses: actions/setup-node@v2.1.2
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#      - name: Setup Secrets
#        uses: secrethub/actions/env-export@v0.2.1
#        env:
#          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}
#          EXPO_ANDROID_KEYSTORE_BASE64: secrethub://denniske/aoe2companion/expo_android_keystore_base64
#          EXPO_ANDROID_KEYSTORE_ALIAS: secrethub://denniske/aoe2companion/expo_android_keystore_alias
#          EXPO_ANDROID_KEYSTORE_PASSWORD: secrethub://denniske/aoe2companion/expo_android_keystore_password
#          EXPO_ANDROID_KEY_PASSWORD: secrethub://denniske/aoe2companion/expo_android_key_password
#
#      - run: yarn
#      - run: turtle setup:android --sdk-version $EXPO_SDK_VERSION > /dev/null
#      - run: |
#          echo $EXPO_ANDROID_KEYSTORE_BASE64 > expo-project.jks.base64
#          base64 --decode expo-project.jks.base64 > expo-project.jks
#          ls -al
#      - run: |
#          turtle build:android
#            --config app.json
#            --release-channel $CHANNEL
#            --keystore-path ./expo-project.jks
#            --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS
#            --type app-bundle
#            -o expo-project-$TRAVIS_COMMIT.aab
#
#      - name: Upload AAB
#        uses: actions/upload-artifact@v1
#        with:
#          name: AAB
#          path: expo-project-$TRAVIS_COMMIT.aab

#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    needs: [build]
#    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0.0')
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1



#  build:
#    name: Build
#    runs-on: ubuntu-latest
##    needs: [publish]
##    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.0')
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#
#      - name: Setup Env
#        uses: ./.github/actions/setup
#      - name: Setup Node
#        uses: actions/setup-node@v2.1.2
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#      - name: Setup Secrets
#        uses: secrethub/actions/env-export@v0.2.1
#        env:
#          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}
#          EXPO_USERNAME: secrethub://denniske/aoe2companion/expo_username
#          EXPO_PASSWORD: secrethub://denniske/aoe2companion/expo_password
#          EXPO_ANDROID_KEYSTORE_BASE64: secrethub://denniske/aoe2companion/expo_android_keystore_base64
#          EXPO_ANDROID_KEYSTORE_ALIAS: secrethub://denniske/aoe2companion/expo_android_keystore_alias
#          EXPO_ANDROID_KEYSTORE_PASSWORD: secrethub://denniske/aoe2companion/expo_android_keystore_password
#          EXPO_ANDROID_KEY_PASSWORD: secrethub://denniske/aoe2companion/expo_android_key_password
#
##      - run: |
##          echo kk \
##          kk
##      - run: >
##          echo kk
##          kk
#
#      - run: npm config set unsafe-perm true
#      - run: yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
#      - run: yarn
#      - run: turtle setup:android --sdk-version $EXPO_SDK_VERSION > /dev/null
#      - run: |
#          echo $EXPO_ANDROID_KEYSTORE_BASE64 > expo-project.jks.base64
#          base64 --decode expo-project.jks.base64 > expo-project.jks
#          ls -al
#      - run: >
#          turtle build:android \
#            --config app.json \
#            --release-channel $CHANNEL \
#            --keystore-path ./expo-project.jks \
#            --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS \
#            --type app-bundle \
#            -o expo-project-$TRAVIS_COMMIT.aab
#
#      - name: Upload AAB
#        uses: actions/upload-artifact@v1
#        with:
#          name: AAB
#          path: expo-project-$TRAVIS_COMMIT.aab

