# https://hackernoon.com/the-only-sane-way-to-setup-fastlane-on-a-mac-4a14cb8549c8

#on: push

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'           # Push events to every tag

name: Build and Publish server
env:
  NODE_VERSION: 12.13.1
jobs:

#  prepare:
#    name: Prepare
#    runs-on: ubuntu-latest
#    steps:
#    - uses: secrethub/actions/env-export@v0.2.1
#      env:
#       SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_DOCKERHUB_CREDENTIAL }}
#       DOCKERHUB_USERNAME: secrethub://denniske/dockerhub/username
#       DOCKERHUB_PASS: secrethub://denniske/dockerhub/password
#    - run: |
#        echo "TRAVIS_BRANCH=$(node deploy/script/clean-tag.js $GITHUB_REF)" >> $GITHUB_ENV

  build-and-publish-server:
#    if: |
#      startsWith(github.ref, 'refs/tags/refetch') ||
#      startsWith(github.ref, 'refs/tags/refetch-again') ||
#      startsWith(github.ref, 'refs/tags/refetch-repair') ||
#      startsWith(github.ref, 'refs/tags/refetch-multiple') ||
#      startsWith(github.ref, 'refs/tags/refetch-late') ||
#      startsWith(github.ref, 'refs/tags/refetch-result') ||
#      startsWith(github.ref, 'refs/tags/import') ||
#      startsWith(github.ref, 'refs/tags/ingest') ||
#      startsWith(github.ref, 'refs/tags/ingest-fast') ||
#      startsWith(github.ref, 'refs/tags/notify') ||
#      startsWith(github.ref, 'refs/tags/proxy') ||
#      startsWith(github.ref, 'refs/tags/rating-history') ||
#      startsWith(github.ref, 'refs/tags/metric') ||
#      startsWith(github.ref, 'refs/tags/api') ||
#      startsWith(github.ref, 'refs/tags/function') ||
#      startsWith(github.ref, 'refs/tags/rank') ||
#      startsWith(github.ref, 'refs/tags/replay')
    if: startsWith(github.ref, 'refs/tags/function')
    name: Build and Publish server Internal
    runs-on: ubuntu-latest
#    needs: prepare
#    env:
#      COMMIT_SHA1: ${{ github.sha }}
#      TRAVIS_BRANCH: ${{ github.ref }}rr
    steps:
#      - run: echo 'general'
#      - run: echo 'general karl'
#        if: startsWith(github.ref, 'refs/tags/karl')
      - uses: actions/checkout@v1
      - uses: ./.github/actions/setup
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: secrethub/actions/env-export@v0.2.1
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_DOCKERHUB_CREDENTIAL }}
          DOCKERHUB_USERNAME: secrethub://denniske/dockerhub/username
          DOCKERHUB_PASS: secrethub://denniske/dockerhub/password
      - run: |
          echo $COMMIT_SHA1
          echo $TRAVIS_BRANCH
          echo $DOCKERHUB_USERNAME
          echo "SERVICE_NAME=$(node deploy/script/service-name-from-tag.js $TRAVIS_BRANCH)" >> $GITHUB_ENV
          echo $SERVICE_NAME
          sudo yarn global add nx
          yarn
          yarn run generate:prisma
          nx build graph
          docker build -f graph/deploy/Dockerfile -t denniske/aoe2companion-$SERVICE_NAME:$COMMIT_SHA1 .
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push denniske/aoe2companion-$SERVICE_NAME:$COMMIT_SHA1
          chmod +x ./graph/deploy/deploy.sh && ./graph/deploy/deploy.sh

#  cond-build-karl:
#    if: startsWith(github.ref, 'refs/tags/karl')
#    name: Cond Build Karl
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo 'karl'
