
on:
  push:
    tags:
      - '*refetch-v*'
      - '*refetch-v*'
      - '*refetch-again-v*'
      - '*refetch-repair-v*'
      - '*refetch-multiple-v*'
      - '*refetch-late-v*'
      - '*refetch-result-v*'
      - '*import-v*'
      - '*import-ongoing-v*'
      - '*ingest-v*'
      - '*ingest-fast-v*'
      - '*notify-v*'
      - '*proxy-v*'
      - '*rating-history-v*'
      - '*metric-v*'
      - '*api-v*'
      - '*function-v*'
      - '*rest-v*'
      - '*rank-v*'
      - '*replay-v*'
      - '*graphql-v*'

name: Server

env:
  NODE_VERSION: 16.13.1

jobs:

  build-and-publish-server:
    name: Build and Publish Server
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Env
        uses: ./.github/actions/setup
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Secrets
        uses: secrethub/actions/env-export@v0.2.1
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_AOE2COMPANION_CREDENTIAL }}
          DOCKERHUB_USERNAME: secrethub://denniske/aoe2companion/dockerhub_username
          DOCKERHUB_PASSWORD: secrethub://denniske/aoe2companion/dockerhub_password
          KUBERNETES_SERVER: secrethub://denniske/aoe2companion/kubernetes_server
          KUBERNETES_TOKEN: secrethub://denniske/aoe2companion/kubernetes_token
          KUBERNETES_CLUSTER_CERTIFICATE: secrethub://denniske/aoe2companion/kubernetes_cluster_certificate
          ID_CI_RSA_BASE64: secrethub://denniske/aoe2companion/id_ci_rsa_base64
          KNOWN_HOSTS_BASE64: secrethub://denniske/aoe2companion/known_hosts_base64
          DATABASE_URL: secrethub://denniske/aoe2companion/database_url
          DATABASE_URL_AOE4: secrethub://denniske/aoe2companion/database_url_aoe4
          ELECTROLYTIC_APP_SECRET: secrethub://denniske/aoe2companion/electrolytic_app_secret
          PUSHER_SECRET_KEY: secrethub://denniske/aoe2companion/pusher_secret_key
          S3_ACCESS_KEY_ID: secrethub://denniske/aoe2companion/aws_access_key_id
          S3_SECRET_ACCESS_KEY: secrethub://denniske/aoe2companion/aws_secret_access_key
          TWITCH_CLIENT_ID: secrethub://denniske/aoe2companion/twitch_client_id
          TWITCH_CLIENT_SECRET: secrethub://denniske/aoe2companion/twitch_client_secret

      - run: echo "SUBDOMAIN=$(node deploy/script/subdomain-from-tag.js $TRAVIS_BRANCH)" >> $GITHUB_ENV
      - run: echo $SUBDOMAIN
      - run: echo "SERVICE_NAME=$(node deploy/script/service-name-from-tag.js $TRAVIS_BRANCH)" >> $GITHUB_ENV
      - run: echo $SERVICE_NAME
      - run: yarn
      - run: yarn run generate:prisma
      - run: npx nx build graph
      - run: docker build -f graph/deploy/Dockerfile -t denniske/aoe2companion-$SERVICE_NAME:$COMMIT_SHA1 .
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker push denniske/aoe2companion-$SERVICE_NAME:$COMMIT_SHA1

      - run: |
          mkdir ~/.ssh
          echo $ID_CI_RSA_BASE64 | base64 --decode > ~/.ssh/id_rsa
          echo $KNOWN_HOSTS_BASE64 | base64 --decode > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
        
          if [[ $SERVICE_NAME == aoe4-* ]] ;
          then
            export DATABASE_URL=$DATABASE_URL_AOE4
          fi

          ssh -o StrictHostKeyChecking=no root@49.12.204.123 dokku config:set --no-restart --global \
            ELECTROLYTIC_APP_SECRET=$ELECTROLYTIC_APP_SECRET \
            PUSHER_SECRET_KEY=$PUSHER_SECRET_KEY \
            S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID \
            S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY \
            TWITCH_CLIENT_ID=$TWITCH_CLIENT_ID \
            TWITCH_CLIENT_SECRET=$TWITCH_CLIENT_SECRET \
            && true
          
          ssh -o StrictHostKeyChecking=no root@49.12.204.123 dokku apps:create $SERVICE_NAME || true
          ssh -o StrictHostKeyChecking=no root@49.12.204.123 dokku config:set --no-restart $SERVICE_NAME SERVICE_NAME=$SERVICE_NAME
          ssh -o StrictHostKeyChecking=no root@49.12.204.123 dokku config:set --no-restart $SERVICE_NAME DATABASE_URL=$DATABASE_URL
          ssh -o StrictHostKeyChecking=no root@49.12.204.123 dokku domains:set $SERVICE_NAME $SUBDOMAIN.${AOE}companion.com
          ssh -o StrictHostKeyChecking=no root@49.12.204.123 dokku git:from-image $SERVICE_NAME denniske/aoe2companion-$SERVICE_NAME:$COMMIT_SHA1

#          dokku config:set --no-restart --encoded node-js-app KEY="$(base64 ~/.ssh/id_rsa)"

#          cd deploy
#
#          export BASE=base
#          if [[ $SERVICE_NAME == aoe4-* ]] ;
#          then
#            export BASE=base4
#          fi

#          envsubst <./docker-compose-single.yml >./docker-compose-single.yml.out && mv ./docker-compose-single.yml.out ./docker-compose-single.yml
#          envsubst <./docker-compose-worker.yml >./docker-compose-worker.yml.out && mv ./docker-compose-worker.yml.out ./docker-compose-worker.yml
#
#          scp -o StrictHostKeyChecking=no docker-compose-worker.yml root@49.12.204.123:/root/docker-compose.yml
#          scp -o StrictHostKeyChecking=no docker-compose-single.yml root@49.12.204.123:/root/service-$SERVICE_NAME.yml
#          scp -o StrictHostKeyChecking=no run.sh root@49.12.204.123:/root/run.sh
#          ssh -o StrictHostKeyChecking=no root@49.12.204.123 sh run.sh

#          export DATABASE_URL=${DATABASE_URL/aoe/aoe4}
#
#          echo $ID_CI_RSA_BASE64 > id_ci_rsa.base64
#          base64 --decode id_ci_rsa.base64 > ~/.ssh/id_rsa
#          echo $KNOWN_HOSTS_BASE64 > known_hosts.base64
#          base64 --decode known_hosts.base64 > ~/.ssh/known_hosts
